### PR TITLE
Fix pattern cache key collision bug

### LINKED ISSUE #10: instable result for a thirdparty testsuite
Hello pygy,
It's me again :-D

Almost like the [peg issue](https://github.com/pygy/LuLPeg/issues/6), I checked [lua-parser](https://github.com/andremm/lua-parser) with LuLPeg : Awsome, all tests passed with lua5.1/5.2 !
...but in fact ... most of the time yes but not always.
It's was so strange, I can resist to inform you !
If you have time, take a look at https://github.com/andremm/lua-parser/issues/2

Regards,

### PR DESCRIPTION
**Pull request by Khatskevich**
This PR closes #10

### CODE REVIEW

**Comment by pygy** [comment]
Hi @Khatskevich, thanks for the patch.

The changes in `API.lua` make total sense to me, but I don't understand the ones in `constructors.lua`. Is it a workaround for a weak tables bug, or do I just need some sleep (I do, it's almost 1am here)?

**Comment by Khatskevich** [comment]
Yes, you are right.
Changes to `constructors.lua` are redundant.

**Comment by Khatskevich** [comment]
Changing `constructors.lua`
Pros:
1. Unified cache key (`__ptid%d`)
Cons:
1. As I understand this prohibits using pattern names like `__ptid%d`

I can refactor the PR. Should I revert the `constructors.lua`?
In that case I would augment the `pt` with `id` straight in `API` in case the `pt` does not have one during `nameify`.

**Comment by pygy** [comment]
Oh, no, you're right, now I get it.

The collisions stem from the fact that `tostring(table)` and `tostring(proxy)` return a stringified version of their memory location. After one pattern is GC'ed, another may be allocated at the same place in memory.

I did need some sleep :-)

Great catch, and great patch!

**Pull request merged**
